# Conda recipe for Magni

package:
  name: magni
  version: '1.6.0'

source:
  fn: magni-1.6.0.tar.gz
  url: https://pypi.python.org/packages/31/2f/d2acf9751010d30cf545418db7ade6c58568bc40269620401bccf8ab720e/magni-1.6.0.tar.gz#md5=d1521fb4e0d0cdd4ee62c898178be1db
  md5: d1521fb4e0d0cdd4ee62c898178be1db

  patches:
    - setup_py_conda.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools >=11.3
  run:
    - python
    - numpy >=1.8
    - pytables >=3.1
    - scipy >=0.14
    - matplotlib >=1.3
    - setuptools >=11.3

test:
  requires:
    - nose

  imports:
    - magni

about:
  home: https://github.com/SIP-AAU/Magni
  license: BSD 2-Clause
  summary: A Python Package for Compressive Sampling Reconstruction of Atomic Force Microscopy Images
  
