# Conda recipe for Magni

package:
  name: magni
  version: '1.5.0'

source:
  fn: magni-1.5.0.tar.gz
  url: https://pypi.python.org/packages/89/62/1f2132f2d215407cadc2f8ce3e000dd4c4f905ee03998b3cea87711f9530/magni-1.5.0.tar.gz
  md5: 72bf820a7c44938a7dce815f98c68939

  patches:
    - setup_py_conda.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools >=11.3
  run:
    - python
    - numpy >=1.8
    - pytables >=3.1
    - scipy >=0.14
    - matplotlib >=1.3
    - setuptools >=11.3

test:
  requires:
    - nose

  imports:
    - magni

about:
  home: https://github.com/SIP-AAU/Magni
  license: BSD 2-Clause
  summary: A Python Package for Compressive Sampling Reconstruction of Atomic Force Microscopy Images
  
